spring:
  datasource:
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/users
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081

grpc:
  client:
    UserService:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT
